
        <table class="table table-bordered col-6 card-body" style="width: auto;height: auto;">
            <tbody id="table">
            <tr>
                <th>Funcionário</th>
                <th>Modelo</th>
                <th>Estado</th>
                <th>Data</th>
                <th>Hora</th>
                
            </tr>
            <tr>
                <td>Juan</td>
                <td>Social</td>
                <td>Perda</td>
                <td>27/05/2025</td>
                <td>09:10</td>
            </tr>
            <tr>
                <td>Juan</td>
                <td>Social</td>
                <td>Perda</td>
                <td>27/05/2025</td>
                <td>09:10</td>
            </tr>
            <tr>
                <td>Juan</td>
                <td>Social</td>
                <td>Perda</td>
                <td>27/05/2025</td>
                <td>09:10</td>
            </tr>
            <tr>
                <td>Juan</td>
                <td>Social</td>
                <td>Perda</td>
                <td>27/05/2025</td>
                <td>09:10</td>
            </tr>
            <tr>
                <td>Juan</td>
                <td>Social</td>
                <td>Perda</td>
                <td>27/05/2025</td>
                <td>09:10</td>
            </tr>
            <tr>
                <td>Juan</td>
                <td>Social</td>
                <td>Perda</td>
                <td>27/05/2025</td>
                <td>09:10</td>
            </tr>
            <tr>
                <td>Juan</td>
                <td>Social</td>
                <td>Perda</td>
                <td>27/05/2025</td>
                <td>09:10</td>
            </tr>
            <tr>
                <td>Juan</td>
                <td>Social</td>
                <td>Perda</td>
                <td>27/05/2025</td>
                <td>09:10</td>
            </tr>
            <tr>
                <td>Juan</td>
                <td>Social</td>
                <td>Perda</td>
                <td>27/05/2025</td>
                <td>09:10</td>
            </tr>
            </tbody>
        </table>
